#! /bin/sh

### BEGIN INIT INFO
# Provides:          hcc_viola
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Viola controler
# Description:       Viola controler
### END INIT INFO
# Location = /etc/init.d/hcc_init
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/etc/viola

. /lib/lsb/init-functions


d_start() {
#su root -c "/etc/hcc/viola/viola"
exec /etc/hcc/viola/viola &
STATUS=$?
    return ${STATUS:-0}
}


d_restart() {
    ret=$?
    return $ret
}

#
# Function that stops the daemon/service.
#
d_stop() {
	    ret=$?
    return $ret
}

#
# Function that prints if Hcloud is started or not
#
d_status() {
    ret=$?
    return $ret
}

    case "$1" in
	start)
	    log_daemon_msg "Starting $DESC"
	    d_start || log_end_msg 1
	    log_end_msg 0
	    ;;
	stop)
	    log_daemon_msg "Stopping $DESC"
	    d_stop || log_end_msg 1
	    log_end_msg 0
	    ;;
	status)
	    log_daemon_msg "$DESC status"
	    d_status
	    log_end_msg 0
	    ;;
	restart)
	    log_daemon_msg "Restart $DESC"
	    d_restart || log_end_msg 1
	    log_end_msg 0
	    ;;
	*)
	    log_success_msg "Usage: $SCRIPTNAME {start|stop|restart|status}"
	    exit 1
	    ;;
    esac

exit 0
